import jsPDF from "jspdf";

export type PdfSection = {
  heading: string;
  body?: string;
  bullets?: string[];
};

export type PdfReport = {
  filename: string;
  title: string;
  subtitle?: string;
  intro?: string;
  highlight?: { label: string; value: string };
  sections: PdfSection[];
};

const BRAND = { r: 60, g: 80, b: 180 };
const NAVY = { r: 28, g: 38, b: 70 };
const MUTED = { r: 110, g: 118, b: 140 };

export function downloadReport(report: PdfReport) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = 0;

  // Header band
  doc.setFillColor(NAVY.r, NAVY.g, NAVY.b);
  doc.rect(0, 0, pageW, 110, "F");

  // Brand mark
  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
  doc.roundedRect(margin, 30, 28, 28, 4, 4, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("A", margin + 14, 49, { align: "center" });

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("AI Energy Intelligence UK", margin + 40, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(200, 210, 235);
  doc.text("aienergyintelligence.co.uk", margin + 40, 56);

  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(report.title, contentW);
  doc.text(titleLines, margin, 88);

  y = 140;

  if (report.subtitle) {
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(report.subtitle, margin, y);
    y += 18;
  }

  if (report.intro) {
    doc.setTextColor(60, 65, 85);
    doc.setFontSize(10.5);
    const lines = doc.splitTextToSize(report.intro, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 10;
  }

  if (report.highlight) {
    doc.setFillColor(245, 247, 252);
    doc.roundedRect(margin, y, contentW, 64, 8, 8, "F");
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(report.highlight.label.toUpperCase(), margin + 16, y + 22);
    doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(report.highlight.value, margin + 16, y + 50);
    y += 84;
  }

  const ensureSpace = (need: number) => {
    if (y + need > pageH - 60) {
      addFooter(doc, pageW, pageH, margin);
      doc.addPage();
      y = margin;
    }
  };

  for (const sec of report.sections) {
    ensureSpace(40);
    doc.setTextColor(NAVY.r, NAVY.g, NAVY.b);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(sec.heading, margin, y);
    // accent underline
    doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
    doc.setLineWidth(2);
    doc.line(margin, y + 4, margin + 28, y + 4);
    y += 22;

    if (sec.body) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(60, 65, 85);
      const lines = doc.splitTextToSize(sec.body, contentW);
      ensureSpace(lines.length * 14);
      doc.text(lines, margin, y);
      y += lines.length * 14 + 6;
    }

    if (sec.bullets) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(60, 65, 85);
      for (const b of sec.bullets) {
        const lines = doc.splitTextToSize(b, contentW - 14);
        ensureSpace(lines.length * 14 + 4);
        doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
        doc.text("•", margin, y);
        doc.setTextColor(60, 65, 85);
        doc.text(lines, margin + 14, y);
        y += lines.length * 14 + 2;
      }
      y += 6;
    }

    y += 6;
  }

  addFooter(doc, pageW, pageH, margin);
  doc.save(report.filename);
}

function addFooter(doc: jsPDF, pageW: number, pageH: number, margin: number) {
  doc.setDrawColor(225, 228, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, pageH - 40, pageW - margin, pageH - 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  doc.text("Generated by AI Energy Intelligence UK — aienergyintelligence.co.uk", margin, pageH - 24);
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  doc.text(date, pageW - margin, pageH - 24, { align: "right" });
}
