
INSERT INTO public.index_sources (organisation, title, url, publication_date, source_type, accessed_at, geographic_coverage, source_class, reliability_status, status, notes)
VALUES
('Environment Agency','RH10 9BD, Digital Realty (UK) Limited: environmental permit issued','https://www.gov.uk/government/publications/rh10-9bd-digital-realty-uk-limited-environmental-permit-issued','2025-06-09','regulator','2026-08-12','individual_facility','primary','primary_verified','published','Standby generation permit for the Crawley campus.'),
('Environment Agency','E14 9YY, Global Switch Limited: environmental permit issued','https://www.gov.uk/government/publications/e14-9yy-global-switch-limited-environmental-permit-issued','2019-06-28','regulator','2026-08-12','individual_facility','primary','primary_verified','published','Permit covering the East India Dock Road site.'),
('Environment Agency','Decision document EPR/DP3906BE/A001 (Equinix LD8, Slough)','https://www.gov.uk/government/publications/dp3906be-equinix-uk-limited-environmental-permit-issued','2023-10-16','regulator','2026-08-12','individual_facility','primary','primary_verified','published','Permit covers 64 MWth generator thermal input, not IT load.'),
('Environment Agency','Decision document EPR/AP3903PD/A001 (VIRTUS Stockley Park)','https://www.gov.uk/government/publications/ap3903pd-virtus-data-centres-environmental-permit-issued','2021-11-16','regulator','2026-08-12','individual_facility','primary','primary_verified','published','Permit granted for London 5 and 6; refused in part for London 7 and 8.'),
('Ministry of Housing, Communities and Local Government','Recovered appeal decision: Manor Farm and land north of Wraysbury Reservoir, Poyle Road, Slough (APP/J0350/W/25/3366043)','https://www.gov.uk/government/publications/recovered-appeal-manor-farm-and-land-to-the-north-of-wraysbury-reservoir-poyle-road-slough-sl3-0aa-ref-appj0350w253366043-10-june-2026','2026-06-10','official','2026-08-12','individual_facility','primary','primary_verified','published','Secretary of State allowed the appeal subject to conditions.'),
('Ministry of Housing, Communities and Local Government','Data Centre Campus, Ampthill Road, Bedford in Central Bedfordshire: Section 35 Direction, Planning Act 2008','https://www.gov.uk/government/publications/data-centre-campus-ampthill-road-bedford-in-central-bedfordshire-section-35-direction','2026-06-15','official','2026-08-12','individual_facility','primary','primary_verified','published','Direction only; no substantive planning decision.'),
('Hertsmere Borough Council','Data centre in Hertsmere given outline permission by planning committee','https://www.hertsmere.gov.uk/news/2025/january/data-centre-in-hertsmere-given-outline-permission-by-planning-committee.aspx','2025-01-23','official','2026-08-12','local_authority','primary','primary_verified','published','Planning authority''s own record of the committee decision.'),
('Bridgend County Borough Council','Officers'' Report, application P/25/247/HYB, former Ford Engine Plant, Bridgend','https://democratic.bridgend.gov.uk/documents/s36191/Officers%20Report_P25247HYB.pdf',NULL,'official','2026-08-12','local_authority','primary','primary_verified','published','Hybrid application; committee decision not confirmed in the document reviewed.'),
('Scottish Government, Planning and Environmental Appeals Division','Case PPA-230-2794, 1 Redheughs Avenue, Edinburgh','https://www.dpea.scotland.gov.uk/CaseDetails.aspx?ID=128582',NULL,'official','2026-08-12','individual_facility','primary','primary_verified','published','Appeal following refusal by City of Edinburgh Council.'),
('Old Oak and Park Royal Development Corporation','Planning Committee report, Unit F, 6 Premier Park Road, London NW10 7NZ (25/0196/FUMOPDC)','https://www.london.gov.uk/programmes-strategies/planning/old-oak-and-park-royal-development-corporation','2026-02-26','official','2026-08-12','local_authority','primary','reliable_secondary','published','Decision date conflicts with a third-party record; not used for publication pending the decision notice.'),
('Rushcliffe Borough Council','Ratcliffe on Soar Power Station Local Development Order - Proposed Revisions, Cabinet report','https://www.rushcliffe.gov.uk/planning-and-growth/planning-policy/local-development-orders/','2026-04-14','official','2026-08-12','local_authority','primary','primary_verified','published','Order revision only; no specific data-centre scheme, operator or capacity.'),
('Harworth Group plc','Harworth and Microsoft receive resolution to grant planning consent for hyperscale data centre at Skelton Grange, Leeds','https://harworthgroup.com/2026/04/27/harworth-and-microsoft-receive-resolution-to-grant-planning-consent-for-hyperscale-data-centre-and-il-space-at-skelton-grange-leeds/','2026-04-27','operator','2026-08-12','individual_facility','primary','reliable_secondary','published','A resolution to grant is not an issued decision notice.')
ON CONFLICT DO NOTHING;

INSERT INTO public.dc_projects
(slug,name,operator,developer,campus_name,town,address_line,postcode,local_authority,nation,region,country,index_region_slug,planning_authority,planning_reference,status,planning_decision,decision_date,facility_type,project_type,ai_relevance,capacity_mw,capacity_unit,capacity_definition,confidence_level,verified,verified_at,last_verified_at,status_publication,display_order,summary,key_facts,sources,duplicate_reviewed,admin_notes)
VALUES
('digital-realty-crawley','Digital Realty Crawley','Digital Realty','Digital Realty (UK) Limited',NULL,'Crawley','Manor Royal','RH10 9BD','Crawley Borough Council','england','South East','United Kingdom','south-east-england','Crawley Borough Council','EPR/EP3022ST/A001 (environmental permit)','operational','Environmental permit issued','2025-06-09','colocation','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',10,'Operational campus at Manor Royal. Verified through the Environment Agency permit for standby generation; the underlying planning consent was not retrieved.','[]'::jsonb,'[{"title":"RH10 9BD, Digital Realty (UK) Limited: environmental permit issued","url":"https://www.gov.uk/government/publications/rh10-9bd-digital-realty-uk-limited-environmental-permit-issued","publisher":"Environment Agency","date":"2025-06-09"}]'::jsonb,true,'Vendor marketing cites 72 MW for one unit; definition unstated, so not recorded.'),
('global-switch-london','Global Switch London','Global Switch','Global Switch Limited',NULL,'London','240 East India Dock Road','E14 9YY','London Borough of Tower Hamlets','england','London','United Kingdom','london','London Borough of Tower Hamlets','EPR/BP3530YR/A001 (environmental permit)','operational','Environmental permit issued','2019-06-28','colocation','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',11,'Long-established operational facility. Verified through the Environment Agency permit; original borough consents not traced.','[]'::jsonb,'[{"title":"E14 9YY, Global Switch Limited: environmental permit issued","url":"https://www.gov.uk/government/publications/e14-9yy-global-switch-limited-environmental-permit-issued","publisher":"Environment Agency","date":"2019-06-28"}]'::jsonb,true,NULL),
('equinix-ld8-slough','Equinix LD8','Equinix','Equinix (UK) Limited',NULL,'Slough',NULL,NULL,'Slough Borough Council','england','South East','United Kingdom','slough-thames-valley','Slough Borough Council','EPR/DP3906BE/A001 (environmental permit)','operational','Environmental permit issued','2023-10-16','colocation','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',12,'Operational Slough facility. The permit covers 64 MWth of generator thermal input, which is not an IT-load figure and is not recorded as capacity.','[]'::jsonb,'[{"title":"Decision document EPR/DP3906BE/A001","url":"https://www.gov.uk/government/publications/dp3906be-equinix-uk-limited-environmental-permit-issued","publisher":"Environment Agency","date":"2023-10-16"}]'::jsonb,true,'Exact postcode not confirmed in the permit.'),
('virtus-stockley-park','VIRTUS Stockley Park campus','VIRTUS Data Centres','Virtus HoldCo Limited','Stockley Park','Uxbridge','Prologis Park, Horton Road, Stockley Park','UB11 1HB','London Borough of Hillingdon','england','London','United Kingdom','london','London Borough of Hillingdon','EPR/AP3903PD/A001 (environmental permit)','operational','Permit granted for London 5 and London 6; refused in part for London 7 and London 8','2021-11-16','colocation','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',13,'Campus counted as one project. London 5 and 6 are permitted and operational; the permit was refused in part for London 7 and 8. That refusal is of the environmental permit, not necessarily of planning consent.','[]'::jsonb,'[{"title":"Decision document EPR/AP3903PD/A001","url":"https://www.gov.uk/government/publications/ap3903pd-virtus-data-centres-environmental-permit-issued","publisher":"Environment Agency","date":"2021-11-16"}]'::jsonb,true,'Planning status of London 7 and 8 not separately verified.'),
('manor-farm-poyle-road-slough','Manor Farm and land north of Wraysbury Reservoir',NULL,'Manor Farm Propco Limited',NULL,'Slough','Poyle Road','SL3 0AA','Slough Borough Council','england','South East','United Kingdom','slough-thames-valley','Ministry of Housing, Communities and Local Government (recovered appeal)','P/10076/013; APP/J0350/W/25/3366043','approved','Appeal allowed by the Secretary of State, subject to conditions','2026-06-10','type_unconfirmed','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',14,'Recovered appeal allowed by the Secretary of State. The end operator is not identified in the decision letter and no capacity figure is given. Battery storage is co-located.','[]'::jsonb,'[{"title":"Recovered appeal decision, Manor Farm, Poyle Road, Slough (APP/J0350/W/25/3366043)","url":"https://www.gov.uk/government/publications/recovered-appeal-manor-farm-and-land-to-the-north-of-wraysbury-reservoir-poyle-road-slough-sl3-0aa-ref-appj0350w253366043-10-june-2026","publisher":"MHCLG","date":"2026-06-10"}]'::jsonb,true,NULL),
('dc01uk-south-mimms','DC01UK, South Mimms','DC01UK','DC01UK',NULL,'South Mimms',NULL,NULL,'Hertsmere Borough Council','england','South East','United Kingdom','south-east-england','Hertsmere Borough Council',NULL,'approved','Outline planning permission granted by planning committee','2025-01-23','type_unconfirmed','data_centre','unknown',NULL,'MW','not_disclosed','medium',true,now(),'2026-08-12','published',15,'Outline permission only. The council cites 87,000 sq m of floorspace; no IT-load or grid-connection figure has been verified. The developer states the site was sold to Equinix in October 2025, which has not been verified from a regulatory filing.','[]'::jsonb,'[{"title":"Data centre in Hertsmere given outline permission by planning committee","url":"https://www.hertsmere.gov.uk/news/2025/january/data-centre-in-hertsmere-given-outline-permission-by-planning-committee.aspx","publisher":"Hertsmere Borough Council","date":"2025-01-23"}]'::jsonb,true,'Council application reference not retrieved from the portal.'),
('vantage-bridgend','Vantage Bridgend campus (former Ford engine plant)','Vantage Data Centers','VDC CWL4 Limited',NULL,'Bridgend','Waterton Industrial Estate','CF31 3PJ','Bridgend County Borough Council','wales','Wales','United Kingdom','wales','Bridgend County Borough Council','P/25/247/HYB','proposed','Hybrid application submitted; no decision confirmed in the officers'' report reviewed',NULL,'type_unconfirmed','data_centre','unknown',NULL,'MW','not_disclosed','medium',false,NULL,'2026-08-12','published',16,'Hybrid planning application submitted. The developer''s own engagement timeline gives construction of building 1 from early 2026 and site completion between 2028 and 2040; those are stated intentions, not verified outcomes.','[]'::jsonb,'[{"title":"Officers'' Report, application P/25/247/HYB","url":"https://democratic.bridgend.gov.uk/documents/s36191/Officers%20Report_P25247HYB.pdf","publisher":"Bridgend County Borough Council"}]'::jsonb,true,'Committee decision and date not confirmed; recheck the council register before changing status.'),
('edinburgh-redheughs-avenue','1 Redheughs Avenue data centre, South Gyle',NULL,NULL,NULL,'Edinburgh','1 Redheughs Avenue','EH12 9RH','City of Edinburgh Council','scotland','Scotland','United Kingdom','scotland','City of Edinburgh Council; Scottish Government DPEA (appeal)','PPA-230-2794 (appeal)','refused','Refused by City of Edinburgh Council; appeal lodged with the DPEA','2026-02-04','type_unconfirmed','data_centre','unknown',NULL,'MW','unclear','medium',true,now(),'2026-08-12','published',17,'Refused by councillors against officer recommendation and now under appeal. A figure of 213 MW has been reported at proposal stage but its definition is unstated, so it is excluded from any capacity total.','[]'::jsonb,'[{"title":"Case PPA-230-2794","url":"https://www.dpea.scotland.gov.uk/CaseDetails.aspx?ID=128582","publisher":"Scottish Government, Planning and Environmental Appeals Division"}]'::jsonb,true,'Council application reference not retrieved; appeal outcome pending.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.dc_projects
(slug,name,operator,developer,campus_name,town,local_authority,nation,region,country,index_region_slug,planning_authority,planning_reference,status,facility_type,project_type,ai_relevance,capacity_unit,capacity_definition,confidence_level,verified,status_publication,display_order,summary,key_facts,sources,duplicate_reviewed,admin_notes)
VALUES
('equinix-wexham-road-slough','Equinix Wexham Road (former AkzoNobel site)','Equinix','Equinix',NULL,'Slough','Slough Borough Council','england','South East','United Kingdom','slough-thames-valley','Slough Borough Council',NULL,'approved','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',20,'Outline consent reported November 2025.','[]'::jsonb,'[]'::jsonb,true,'Held: only news reporting. Need the Slough BC decision notice and application reference.'),
('bedford-ampthill-road-campus','Data Centre Campus, Ampthill Road, Bedford',NULL,'Questpit Limited',NULL,'Bedford','Central Bedfordshire Council','england','East of England','United Kingdom',NULL,'MHCLG (nationally significant)','Section 35 Direction','proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','medium',false,'draft',21,'Section 35 direction issued designating the scheme nationally significant. No planning application decision.','[]'::jsonb,'[{"title":"Section 35 Direction, Planning Act 2008","url":"https://www.gov.uk/government/publications/data-centre-campus-ampthill-road-bedford-in-central-bedfordshire-section-35-direction","publisher":"MHCLG","date":"2026-06-15"}]'::jsonb,true,'Held: Central Bedfordshire sits outside the nine index regions. Decide the regional treatment before publishing.'),
('kao-data-harlow-plot-f','Kao Data Harlow, Plot F (KLON-07 and KLON-08)','Kao Data','KD 6 Limited','Kao Data Harlow','Harlow','Harlow Council','england','South East','United Kingdom','south-east-england','Harlow Council (Local Development Order)',NULL,'proposed','colocation','data_centre','unknown','MW','not_disclosed','low',false,'draft',22,'Confirmation of compliance application under the London Road North Local Development Order, March 2025. Floorspace disclosed; no power figure.','[]'::jsonb,'[]'::jsonb,true,'Held: consultant-authored application document only, outcome not confirmed.'),
('premier-park-park-royal','Premier Park data centre, Park Royal',NULL,'SEGRO',NULL,'London','Old Oak and Park Royal Development Corporation','england','London','United Kingdom','london','OPDC','25/0196/FUMOPDC','approved','type_unconfirmed','data_centre','unknown','MW','not_disclosed','medium',false,'draft',23,'Committee report for a 25,281 sq m GEA scheme.','[]'::jsonb,'[]'::jsonb,true,'Held: decision date conflicts between the aggregator record (6 Feb 2026) and the committee meeting (26 Feb 2026). Need the decision notice.'),
('aws-maylands-avenue-hemel','Amazon Web Services, Plot 3 Maylands Avenue','Amazon Web Services','Amazon',NULL,'Hemel Hempstead','Dacorum Borough Council','england','South East','United Kingdom','south-east-england','Dacorum Borough Council',NULL,'proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',24,'Application supporting documents dated January 2026.','[]'::jsonb,'[]'::jsonb,true,'Held: supporting technical document only, no application reference or decision.'),
('northtree-hemel-hempstead','Northtree conversion, Hemel Hempstead',NULL,'Northtree',NULL,'Hemel Hempstead','Dacorum Borough Council','england','South East','United Kingdom','south-east-england','Dacorum Borough Council',NULL,'approved','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',25,'Outline approval of a self-storage to data-centre conversion reported August 2025.','[]'::jsonb,'[]'::jsonb,true,'Held: local press only.'),
('ratcliffe-on-soar-ldo','Ratcliffe-on-Soar power station site',NULL,NULL,NULL,'Ratcliffe-on-Soar','Rushcliffe Borough Council','england','East Midlands','United Kingdom','midlands','Rushcliffe Borough Council','Local Development Order (revision)','proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',26,'The council is revising a Local Development Order that could permit data-centre uses. No scheme, operator or capacity exists.','[]'::jsonb,'[{"title":"Ratcliffe on Soar Power Station Local Development Order - Proposed Revisions","url":"https://www.rushcliffe.gov.uk/planning-and-growth/planning-policy/local-development-orders/","publisher":"Rushcliffe Borough Council","date":"2026-04-14"}]'::jsonb,true,'Held: a site allocation, not a project. Track only.'),
('kao-data-stockport','Kao Data Kenwood Point, Stockport','Kao Data','Kao Data',NULL,'Stockport','Stockport Metropolitan Borough Council','england','North West','United Kingdom','north-west-england','Stockport Metropolitan Borough Council','DC/090411','approved','colocation','data_centre','unknown','MW','unclear','low',false,'draft',27,'Committee approval reported March 2024. A 40 MW figure appears in the operator''s press release without a stated definition.','[]'::jsonb,'[]'::jsonb,true,'Held: operator press release only. Need the Stockport decision notice and a capacity definition.'),
('stellium-cobalt-park','Cobalt Data Centre Campus (Stellium)','Stellium Datacenters','Stellium','Cobalt Park','Wallsend','North Tyneside Council','england','North East','United Kingdom','north-east-and-yorkshire','North Tyneside Council','24/01678/FULM','approved','colocation','data_centre','unknown','MW','not_disclosed','low',false,'draft',28,'Plant replacement application recorded on a third-party aggregator.','[]'::jsonb,'[]'::jsonb,true,'Held: aggregator record only; council portal not opened. Campus capacity not disclosed.'),
('cambois-data-centre-campus','Cambois data centre campus',NULL,NULL,NULL,'Cambois','Northumberland County Council','england','North East','United Kingdom','north-east-and-yorkshire','Northumberland County Council','24/04112/OUTES','proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',29,'Outline application reported to committee on 4 March 2025. Floorspace of up to 540,000 sq m cited; no power figure.','[]'::jsonb,'[]'::jsonb,true,'Held: source URL returned 403 on re-check and the outcome is unconfirmed. Do not record as approved.'),
('skelton-grange-leeds','Skelton Grange, Leeds','Microsoft','Harworth Group',NULL,'Leeds','Leeds City Council','england','Yorkshire and the Humber','United Kingdom','north-east-and-yorkshire','Leeds City Council',NULL,'proposed','hyperscale','data_centre','unknown','MW','not_disclosed','medium',false,'draft',30,'Harworth Group reports a resolution to grant planning consent, dated 27 April 2026. A resolution to grant is not an issued decision notice.','[]'::jsonb,'[{"title":"Harworth and Microsoft receive resolution to grant planning consent, Skelton Grange","url":"https://harworthgroup.com/2026/04/27/harworth-and-microsoft-receive-resolution-to-grant-planning-consent-for-hyperscale-data-centre-and-il-space-at-skelton-grange-leeds/","publisher":"Harworth Group plc","date":"2026-04-27"}]'::jsonb,true,'Held: reported floorspace conflicts between outlets (500,000 vs 424,000 sq ft) and the decision notice has not been seen.'),
('deep-green-bradford','Deep Green Bradford, Listerhills Road','Deep Green Technologies','Deep Green Technologies',NULL,'Bradford','City of Bradford Metropolitan District Council','england','Yorkshire and the Humber','United Kingdom','north-east-and-yorkshire','City of Bradford Metropolitan District Council',NULL,'approved','edge','data_centre','unknown','MW','unclear','low',false,'draft',31,'Consent reported May 2026, with heat reuse into the Bradford Energy Centre. A 5.6 MW figure is reported without a stated definition.','[]'::jsonb,'[]'::jsonb,true,'Held: trade press only; council decision notice not retrieved.'),
('atlasedge-salford','AtlasEdge Colombus Way, Salford','AtlasEdge','AtlasEdge',NULL,'Salford','Salford City Council','england','North West','United Kingdom','north-west-england','Salford City Council',NULL,'approved','colocation','data_centre','unknown','MW','not_disclosed','low',false,'draft',32,'Permission reported December 2022 for two units of about 37,000 sq ft each.','[]'::jsonb,'[]'::jsonb,true,'Held: trade press only.'),
('teledata-wythenshawe','Teledata Wythenshawe','Teledata UK','Teledata UK',NULL,'Manchester','Manchester City Council','england','North West','United Kingdom','north-west-england','Manchester City Council',NULL,'approved','colocation','data_centre','unknown','MW','not_disclosed','low',false,'draft',33,'Approval reported October 2023 for a 45,000 sq ft facility.','[]'::jsonb,'[]'::jsonb,true,'Held: trade press only. Also check whether Datum and Teledata are the same operator.'),
('ngd-newport-campus','Next Generation Data Newport campus','Next Generation Data','Next Generation Data','Imperial Park','Newport','Newport City Council','wales','Wales','United Kingdom','wales','Newport City Council',NULL,'operational','colocation','data_centre','unknown','MW','unclear','low',false,'draft',34,'Long-operational campus. A new 80 MW building has been reported but not verified against a planning decision, and the figure''s definition is unstated.','[]'::jsonb,'[]'::jsonb,false,'Held: trade press only. Possible overlap with the Vantage Bridgend and earlier Vantage Cardiff consultation records.'),
('haspielaw-farm-hamilton','Haspielaw Farm, Hamilton',NULL,NULL,NULL,'Hamilton','South Lanarkshire Council','scotland','Scotland','United Kingdom','scotland','South Lanarkshire Council','P/25/0490','proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',35,'Screening opinion request only, well short of a determined application.','[]'::jsonb,'[]'::jsonb,true,'Held: portal link did not return a readable response on re-check.'),
('greenscale-foyle-port','GreenScale, Foyle Port','GreenScale','GreenScale','Foyle Port','Londonderry','Derry City and Strabane District Council','northern_ireland','Northern Ireland','United Kingdom','northern-ireland','Derry City and Strabane District Council',NULL,'proposed','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',36,'Described on a planning consultancy''s case-study page as having reached planning submission.','[]'::jsonb,'[]'::jsonb,false,'Held: consultant marketing page only. Possible duplicate of, or a phase within, the Atlantic Hub Foyle Port campus.'),
('atlantic-hub-foyle-port','Atlantic Hub, Foyle Port','Atlantic Hub','Atlantic Hub / Foyle Port','Atlantic Hub','Londonderry','Derry City and Strabane District Council','northern_ireland','Northern Ireland','United Kingdom','northern-ireland','Derry City and Strabane District Council',NULL,'approved','type_unconfirmed','data_centre','unknown','MW','not_disclosed','low',false,'draft',37,'Outline permission reported June 2020 and detailed permission for the first building reported September 2024.','[]'::jsonb,'[]'::jsonb,false,'Held: news and trade press only; no council application references for either decision.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.index_change_log (entity_type, entity_id, field_name, previous_value, new_value, reason, changed_by_label, methodology_version, is_public)
SELECT 'dc_project', p.id, 'record', NULL,
       p.name || ' - ' || p.status || ' (' || p.status_publication || ')',
       CASE WHEN p.status_publication = 'published'
            THEN 'New project record added and published; primary source from the planning or permitting authority verified.'
            ELSE 'New project record added as a private draft; evidence insufficient for publication.' END,
       'Editorial team', 'v1.0', true
FROM public.dc_projects p
WHERE p.created_at > now() - interval '5 minutes';
